# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/bytes_experience_replay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/bytes_experience_replay.proto',
  package='experience_replay',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&protobuf/bytes_experience_replay.proto\x12\x11\x65xperience_replay\"6\n\x0cObservations\x12\x12\n\nvisual_obs\x18\x01 \x01(\x0c\x12\x12\n\nvector_obs\x18\x02 \x01(\x0c\"\x1a\n\x07\x41\x63tions\x12\x0f\n\x07\x61\x63tions\x18\x03 \x01(\x0c\"\x1a\n\x07Rewards\x12\x0f\n\x07rewards\x18\x04 \x01(\x0c\"h\n\x04Info\x12\x1b\n\x0fvisual_obs_spec\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x1b\n\x0fvector_obs_spec\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x0b\x61\x63tion_spec\x18\x07 \x01(\x05\x12\x11\n\tnum_steps\x18\x08 \x01(\x05\x62\x06proto3')
)




_OBSERVATIONS = _descriptor.Descriptor(
  name='Observations',
  full_name='experience_replay.Observations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='visual_obs', full_name='experience_replay.Observations.visual_obs', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector_obs', full_name='experience_replay.Observations.vector_obs', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=115,
)


_ACTIONS = _descriptor.Descriptor(
  name='Actions',
  full_name='experience_replay.Actions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='experience_replay.Actions.actions', index=0,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=143,
)


_REWARDS = _descriptor.Descriptor(
  name='Rewards',
  full_name='experience_replay.Rewards',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rewards', full_name='experience_replay.Rewards.rewards', index=0,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=171,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='experience_replay.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='visual_obs_spec', full_name='experience_replay.Info.visual_obs_spec', index=0,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector_obs_spec', full_name='experience_replay.Info.vector_obs_spec', index=1,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_spec', full_name='experience_replay.Info.action_spec', index=2,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_steps', full_name='experience_replay.Info.num_steps', index=3,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=277,
)

DESCRIPTOR.message_types_by_name['Observations'] = _OBSERVATIONS
DESCRIPTOR.message_types_by_name['Actions'] = _ACTIONS
DESCRIPTOR.message_types_by_name['Rewards'] = _REWARDS
DESCRIPTOR.message_types_by_name['Info'] = _INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Observations = _reflection.GeneratedProtocolMessageType('Observations', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATIONS,
  '__module__' : 'protobuf.bytes_experience_replay_pb2'
  # @@protoc_insertion_point(class_scope:experience_replay.Observations)
  })
_sym_db.RegisterMessage(Observations)

Actions = _reflection.GeneratedProtocolMessageType('Actions', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONS,
  '__module__' : 'protobuf.bytes_experience_replay_pb2'
  # @@protoc_insertion_point(class_scope:experience_replay.Actions)
  })
_sym_db.RegisterMessage(Actions)

Rewards = _reflection.GeneratedProtocolMessageType('Rewards', (_message.Message,), {
  'DESCRIPTOR' : _REWARDS,
  '__module__' : 'protobuf.bytes_experience_replay_pb2'
  # @@protoc_insertion_point(class_scope:experience_replay.Rewards)
  })
_sym_db.RegisterMessage(Rewards)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'protobuf.bytes_experience_replay_pb2'
  # @@protoc_insertion_point(class_scope:experience_replay.Info)
  })
_sym_db.RegisterMessage(Info)


_INFO.fields_by_name['visual_obs_spec']._options = None
_INFO.fields_by_name['vector_obs_spec']._options = None
# @@protoc_insertion_point(module_scope)
