# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/experience_replay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/experience_replay.proto',
  package='experience_replay',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n protobuf/experience_replay.proto\x12\x11\x65xperience_replay\"f\n\nTrajectory\x12\x16\n\nvisual_obs\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x16\n\nvector_obs\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x13\n\x07\x61\x63tions\x18\x03 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x07rewards\x18\x04 \x03(\x02\x42\x02\x10\x01\"h\n\x04Info\x12\x1b\n\x0fvisual_obs_spec\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x1b\n\x0fvector_obs_spec\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x0b\x61\x63tion_spec\x18\x07 \x01(\x05\x12\x11\n\tnum_steps\x18\x08 \x01(\x05')
)




_TRAJECTORY = _descriptor.Descriptor(
  name='Trajectory',
  full_name='experience_replay.Trajectory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='visual_obs', full_name='experience_replay.Trajectory.visual_obs', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector_obs', full_name='experience_replay.Trajectory.vector_obs', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='experience_replay.Trajectory.actions', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rewards', full_name='experience_replay.Trajectory.rewards', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=157,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='experience_replay.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='visual_obs_spec', full_name='experience_replay.Info.visual_obs_spec', index=0,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector_obs_spec', full_name='experience_replay.Info.vector_obs_spec', index=1,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_spec', full_name='experience_replay.Info.action_spec', index=2,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_steps', full_name='experience_replay.Info.num_steps', index=3,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=263,
)

DESCRIPTOR.message_types_by_name['Trajectory'] = _TRAJECTORY
DESCRIPTOR.message_types_by_name['Info'] = _INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trajectory = _reflection.GeneratedProtocolMessageType('Trajectory', (_message.Message,), {
  'DESCRIPTOR' : _TRAJECTORY,
  '__module__' : 'protobuf.experience_replay_pb2'
  # @@protoc_insertion_point(class_scope:experience_replay.Trajectory)
  })
_sym_db.RegisterMessage(Trajectory)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'protobuf.experience_replay_pb2'
  # @@protoc_insertion_point(class_scope:experience_replay.Info)
  })
_sym_db.RegisterMessage(Info)


_TRAJECTORY.fields_by_name['visual_obs']._options = None
_TRAJECTORY.fields_by_name['vector_obs']._options = None
_TRAJECTORY.fields_by_name['actions']._options = None
_TRAJECTORY.fields_by_name['rewards']._options = None
_INFO.fields_by_name['visual_obs_spec']._options = None
_INFO.fields_by_name['vector_obs_spec']._options = None
# @@protoc_insertion_point(module_scope)
